# Warna hasil matugen — dioverwrite tiap ganti wallpaper
background-color={{colors.surface.dark.hex}}ee
text-color={{colors.on_surface.dark.hex}}
border-color={{colors.primary.dark.hex}}

[urgency=high]
border-color={{colors.error.dark.hex}}
text-color={{colors.error.dark.hex}}
default-timeout=0
