# Theme Metadata — furina
name=furina
display_name=Furina
version=1.0
author=risqinf
variant=dark
accent=#9370DB

# Preview
preview=wallpaper/desktop-wallpaper.png

# Wallpapers
wallpaper_type=static
wallpaper_dir=wallpaper/gallery

[features]
live_wallpaper=false
dynamic_colors=true

description=Furina theme
